# Generated by Django 5.2.17 on 2026-08-22 23:27

import accounts.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='รหัสหน่วย')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อหน่วย')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounts.unit', verbose_name='หน่วยเหนือ')),
            ],
            options={
                'verbose_name': 'หน่วยงาน',
                'verbose_name_plural': 'หน่วยงาน',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[accounts.models.validate_allowed_email_domain], verbose_name='อีเมลหน่วย')),
                ('service_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='หมายเลขประจำตัว')),
                ('rank', models.CharField(blank=True, max_length=50, verbose_name='ยศ')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='ตำแหน่ง')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='โทรศัพท์')),
                ('is_infosec_officer', models.BooleanField(default=False, help_text='จัดกิจกรรมเป็นข้อมูลอ่อนไหวได้ (SRS SR-07)', verbose_name='เจ้าหน้าที่ความมั่นคงสารสนเทศ')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='accounts.unit', verbose_name='สังกัด')),
            ],
            options={
                'verbose_name': 'ผู้ใช้',
                'verbose_name_plural': 'ผู้ใช้',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
