# Generated by Django 5.2.17 on 2026-08-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='ใช้กับบัญชีที่นำเข้าและบัญชีทดลอง ห้ามปิดจนกว่าผู้ใช้จะตั้งรหัสผ่านของตนเอง', verbose_name='ต้องเปลี่ยนรหัสผ่านเมื่อเข้าสู่ระบบครั้งถัดไป'),
        ),
    ]
