# Generated by Django 5.2.17 on 2026-09-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_must_change_password"),
        ("resources", "0005_alter_blackout_room_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorite_resources",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorited_by",
                to="resources.resource",
                verbose_name="ห้องโปรด",
            ),
        ),
    ]
