# Generated by Django 5.2.17 on 2026-10-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_favorite_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_lodging_student',
            field=models.BooleanField(db_default=False, default=False, help_text='บัญชีอัตโนมัติจาก Google ไม่มีสิทธิ์จองห้องหรือจัดการบริการอื่น', verbose_name='บัญชีนักเรียนจองเตียงเท่านั้น'),
        ),
    ]
