# Generated by Django 5.2.17 on 2026-08-24 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='เวลา')),
                ('entity', models.CharField(db_index=True, max_length=100, verbose_name='ชนิดข้อมูล')),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='รหัสข้อมูล')),
                ('action', models.CharField(db_index=True, max_length=100, verbose_name='เหตุการณ์')),
                ('before', models.JSONField(blank=True, null=True, verbose_name='ก่อนเปลี่ยน')),
                ('after', models.JSONField(blank=True, null=True, verbose_name='หลังเปลี่ยน')),
                ('ip', models.CharField(blank=True, max_length=45, verbose_name='IP')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='ผู้กระทำ')),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit log',
                'ordering': ['-at', '-pk'],
                'indexes': [models.Index(fields=['entity', 'entity_id', 'at'], name='audit_audit_entity_863a56_idx')],
            },
        ),
    ]
