# Generated by Django 5.2.17 on 2026-08-22 23:27

import django.contrib.postgres.constraints
from django.contrib.postgres.operations import BtreeGistExtension
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ต้องมี btree_gist เพื่อให้ GiST เปรียบเทียบ uuid ด้วย = และ <> ได้ (SRS FR-35)
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('responsible_name', models.CharField(max_length=200, verbose_name='ผู้รับผิดชอบ (ชื่อ-ตำแหน่ง)')),
                ('responsible_phone', models.CharField(max_length=30, verbose_name='โทรศัพท์ผู้รับผิดชอบ')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อกิจกรรม / วิชา')),
                ('purpose', models.CharField(choices=[('teaching', 'สอน'), ('meeting', 'ประชุม'), ('training', 'อบรม'), ('exam', 'สอบ'), ('ceremony', 'พิธี'), ('other', 'อื่น ๆ')], default='teaching', max_length=20, verbose_name='ประเภทการใช้งาน')),
                ('start_at', models.DateTimeField(verbose_name='เริ่ม')),
                ('end_at', models.DateTimeField(verbose_name='สิ้นสุด')),
                ('attendees', models.PositiveIntegerField(default=1, verbose_name='จำนวนผู้เข้าร่วม')),
                ('attendee_level', models.CharField(blank=True, max_length=100, verbose_name='ระดับ/ชั้นผู้เข้าร่วม')),
                ('layout', models.CharField(blank=True, max_length=100, verbose_name='รูปแบบจัดโต๊ะ')),
                ('fixed_equipment_needed', models.TextField(blank=True, verbose_name='อุปกรณ์ประจำห้องที่ต้องใช้')),
                ('has_external_attendees', models.BooleanField(default=False, verbose_name='มีผู้เข้าร่วมจากภายนอก')),
                ('external_attendees_note', models.CharField(blank=True, max_length=200, verbose_name='จำนวน/หน่วยของผู้เข้าร่วมภายนอก')),
                ('visibility', models.CharField(choices=[('normal', 'ปกติ (ทั่วไปเห็น ไม่ว่าง + หน่วย)'), ('restricted', 'จำกัด (ทั่วไปเห็นแค่ ไม่ว่าง)'), ('sensitive', 'อ่อนไหว (ล็อกโดย จนท.ความมั่นคงสารสนเทศ)')], default='normal', max_length=20, verbose_name='ระดับการมองเห็น')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('request_status', models.CharField(choices=[('draft', 'ร่าง'), ('pending', 'รออนุมัติ'), ('approved', 'อนุมัติ'), ('rejected', 'ปฏิเสธ'), ('cancelled', 'ยกเลิก'), ('expired', 'หมดอายุ')], default='draft', max_length=20, verbose_name='สถานะคำขอ')),
                ('usage_status', models.CharField(choices=[('upcoming', 'รอใช้งาน'), ('used', 'ใช้งานแล้ว'), ('no_show', 'ไม่มาใช้'), ('displaced', 'ถูกย้าย'), ('room_unavailable', 'ห้องใช้งานไม่ได้')], default='upcoming', max_length=20, verbose_name='สถานะการใช้งาน')),
                ('is_urgent', models.BooleanField(default=False, help_text='ตั้งโดยระบบตาม FR-23', verbose_name='คำขอเร่งด่วน')),
                ('revision', models.PositiveIntegerField(default=1, help_text='เพิ่มทุกครั้งที่แก้ไข ใช้กัน amendment ทับข้อมูลเก่า', verbose_name='รุ่นข้อมูล')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='ส่งคำขอเมื่อ')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='ผู้จอง')),
                ('room', models.ForeignKey(limit_choices_to={'resource_type': 'room'}, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='resources.resource', verbose_name='ห้อง')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.unit', verbose_name='หน่วยงานผู้ขอ')),
            ],
            options={
                'verbose_name': 'การจอง',
                'verbose_name_plural': 'การจอง',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hold', django.contrib.postgres.fields.ranges.DateTimeRangeField(verbose_name='ช่วงถือครอง (รวม buffer)')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='ปลดเมื่อ')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='bookings.booking', verbose_name='การจอง')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='resources.resource', verbose_name='ทรัพยากร')),
            ],
            options={
                'verbose_name': 'ช่วงถือครองทรัพยากร',
                'verbose_name_plural': 'ช่วงถือครองทรัพยากร',
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'start_at'], name='bookings_bo_room_id_d0fe0c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['requester', 'start_at'], name='bookings_bo_request_d1caa3_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['request_status'], name='bookings_bo_request_9b6fb1_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='booking_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='bookingresource',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('released_at__isnull', True)), expressions=[('resource', '='), ('booking', '<>'), ('hold', '&&')], name='excl_overlapping_holds'),
        ),
        migrations.AddConstraint(
            model_name='bookingresource',
            constraint=models.CheckConstraint(condition=models.Q(('hold__isempty', True), _negated=True), name='hold_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='bookingresource',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('booking', 'resource'), name='uniq_active_hold_per_booking_resource'),
        ),
    ]
