# Generated by Django 5.2.17 on 2026-08-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='equipment',
            field=models.ManyToManyField(blank=True, limit_choices_to={'resource_type': 'equipment'}, related_name='bookings_as_equipment', to='resources.resource', verbose_name='อุปกรณ์ส่วนกลางที่ขอ'),
        ),
    ]
