# Generated by Django 5.2.17 on 2026-08-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='decision_reason',
            field=models.TextField(blank=True, verbose_name='เหตุผลการพิจารณาล่าสุด'),
        ),
        migrations.AddField(
            model_name='booking',
            name='sla_escalated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เปิดสิทธิ์ผู้อนุมัติสำรองเมื่อ'),
        ),
    ]
