# Generated by Django 5.2.17 on 2026-08-23 22:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookings', '0003_booking_decision_reason_booking_sla_escalated_at'),
        ('resources', '0002_blackout_resourceoutage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='series_index',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ลำดับในชุด'),
        ),
        migrations.CreateModel(
            name='BookingSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('freq', models.CharField(choices=[('weekly', 'รายสัปดาห์'), ('workdays', 'ทุกวันราชการ'), ('custom', 'กำหนดวันเอง')], max_length=20, verbose_name='รูปแบบ')),
                ('weekdays', models.JSONField(blank=True, default=list, verbose_name='วันในสัปดาห์')),
                ('custom_dates', models.JSONField(blank=True, default=list, verbose_name='วันที่กำหนดเอง')),
                ('start_date', models.DateField(verbose_name='วันที่เริ่ม')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='วันที่สิ้นสุด')),
                ('requested_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='จำนวนครั้งที่ขอ')),
                ('time_start', models.TimeField(verbose_name='เวลาเริ่ม')),
                ('time_end', models.TimeField(verbose_name='เวลาสิ้นสุด')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_series', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_series', to='resources.resource', verbose_name='ห้อง')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_series', to='accounts.unit', verbose_name='หน่วยงาน')),
            ],
            options={
                'verbose_name': 'ชุดการจอง',
                'verbose_name_plural': 'ชุดการจอง',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='bookings.bookingseries', verbose_name='ชุดการจอง'),
        ),
        migrations.CreateModel(
            name='SeriesSkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occur_date', models.DateField(verbose_name='วันที่ไม่ได้สร้าง')),
                ('kind', models.CharField(choices=[('blackout', 'ข้ามตามปฏิทินส่วนกลาง'), ('conflict', 'เวลาชน'), ('conflict_at_submit', 'มีผู้จองตัดหน้าขณะยืนยัน')], max_length=30, verbose_name='สาเหตุ')),
                ('reason', models.CharField(max_length=200, verbose_name='รายละเอียด')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skips', to='bookings.bookingseries', verbose_name='ชุดการจอง')),
            ],
            options={
                'verbose_name': 'ครั้งที่ข้ามในชุด',
                'verbose_name_plural': 'ครั้งที่ข้ามในชุด',
                'ordering': ['occur_date', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('series', 'occur_date'), name='uniq_series_skip_date')],
            },
        ),
    ]
