# Generated by Django 5.2.17 on 2026-08-24 02:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_series_index_bookingseries_booking_series_and_more'),
        ('resources', '0002_blackout_resourceoutage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'รออนุมัติ'), ('approved', 'อนุมัติ'), ('rejected', 'ปฏิเสธ'), ('expired', 'หมดอายุ'), ('withdrawn', 'ถอน')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('base_revision', models.PositiveIntegerField(verbose_name='รุ่นข้อมูลตั้งต้น')),
                ('proposed_start_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาเริ่มที่เสนอ')),
                ('proposed_end_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาสิ้นสุดที่เสนอ')),
                ('proposed_attendees', models.PositiveIntegerField(blank=True, null=True, verbose_name='จำนวนผู้เข้าร่วมที่เสนอ')),
                ('proposed_has_external', models.BooleanField(blank=True, null=True, verbose_name='มีผู้เข้าร่วมภายนอกที่เสนอ')),
                ('proposed_external_note', models.CharField(blank=True, max_length=200, verbose_name='รายละเอียดผู้เข้าร่วมภายนอกที่เสนอ')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='เหตุผลของผู้ขอ')),
                ('decision_reason', models.TextField(blank=True, verbose_name='เหตุผลการพิจารณา')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='ยื่นเมื่อ')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='พิจารณาเมื่อ')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='เร่งด่วน')),
                ('sla_escalated_at', models.DateTimeField(blank=True, null=True, verbose_name='เปิดสิทธิ์ผู้อนุมัติสำรองเมื่อ')),
            ],
            options={
                'verbose_name': 'คำขอแก้ไขการจอง',
                'verbose_name_plural': 'คำขอแก้ไขการจอง',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Preemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordered_by_position', models.CharField(max_length=200, verbose_name='ตำแหน่งผู้สั่ง ณ วันสั่ง')),
                ('reference_no', models.CharField(max_length=100, verbose_name='เลขอ้างอิงคำสั่ง/หนังสือ')),
                ('reason', models.CharField(max_length=300, verbose_name='เหตุผล')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='รับทราบเมื่อ')),
                ('deemed_acknowledged', models.BooleanField(default=False, verbose_name='ถือว่ารับทราบแล้ว')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
            ],
            options={
                'verbose_name': 'การบังคับย้าย',
                'verbose_name_plural': 'การบังคับย้าย',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='bookingresource',
            name='uniq_active_hold_per_booking_resource',
        ),
        migrations.AddField(
            model_name='bookingamendment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='bookings.booking', verbose_name='การจอง'),
        ),
        migrations.AddField(
            model_name='bookingamendment',
            name='proposed_equipment',
            field=models.ManyToManyField(blank=True, limit_choices_to={'resource_type': 'equipment'}, related_name='proposed_equipment_amendments', to='resources.resource', verbose_name='อุปกรณ์ชุดเต็มที่เสนอ'),
        ),
        migrations.AddField(
            model_name='bookingamendment',
            name='proposed_room',
            field=models.ForeignKey(blank=True, limit_choices_to={'resource_type': 'room'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposed_amendments', to='resources.resource', verbose_name='ห้องที่เสนอ'),
        ),
        migrations.AddField(
            model_name='bookingamendment',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_booking_amendments', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ยื่น'),
        ),
        migrations.AddField(
            model_name='bookingresource',
            name='amendment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='bookings.bookingamendment', verbose_name='คำขอแก้ไข'),
        ),
        migrations.AddConstraint(
            model_name='bookingresource',
            constraint=models.UniqueConstraint(condition=models.Q(('amendment__isnull', True), ('released_at__isnull', True)), fields=('booking', 'resource'), name='uniq_active_hold_per_booking_resource'),
        ),
        migrations.AddConstraint(
            model_name='bookingresource',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('amendment', 'resource'), name='uniq_active_amendment_hold'),
        ),
        migrations.AddField(
            model_name='preemption',
            name='displaced',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preemption_as_displaced', to='bookings.booking', verbose_name='การจองที่ถูกย้าย'),
        ),
        migrations.AddField(
            model_name='preemption',
            name='incoming',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preemption_as_incoming', to='bookings.booking', verbose_name='การจองที่เข้าแทน'),
        ),
        migrations.AddField(
            model_name='preemption',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordered_preemptions', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สั่ง'),
        ),
        migrations.AddField(
            model_name='preemption',
            name='replacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preemption_as_replacement', to='bookings.booking', verbose_name='การจองทดแทน'),
        ),
        migrations.AddConstraint(
            model_name='bookingamendment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('booking',), name='one_pending_amendment_per_booking'),
        ),
        migrations.AddConstraint(
            model_name='bookingamendment',
            constraint=models.UniqueConstraint(fields=('id', 'booking'), name='uniq_amendment_id_booking'),
        ),
        migrations.AddConstraint(
            model_name='bookingamendment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('proposed_end_at__isnull', True), ('proposed_start_at__isnull', True)), models.Q(('proposed_end_at__isnull', False), ('proposed_start_at__isnull', False)), _connector='OR'), name='amendment_times_together'),
        ),
        migrations.RunSQL(
            sql=(
                'ALTER TABLE bookings_bookingresource '
                'ADD CONSTRAINT fk_amendment_same_booking '
                'FOREIGN KEY (amendment_id, booking_id) '
                'REFERENCES bookings_bookingamendment (id, booking_id) '
                'DEFERRABLE INITIALLY DEFERRED;'
            ),
            reverse_sql=(
                'ALTER TABLE bookings_bookingresource '
                'DROP CONSTRAINT fk_amendment_same_booking;'
            ),
        ),
    ]
