# Generated by Django 5.2.17 on 2026-08-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookingamendment_preemption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('title', 'ชื่อกิจกรรม / วิชา'), ('responsible_name', 'ผู้รับผิดชอบ'), ('responsible_phone', 'โทรศัพท์ผู้รับผิดชอบ'), ('attendee_level', 'ระดับ/ชั้นผู้เข้าร่วม'), ('layout', 'รูปแบบจัดโต๊ะ')], max_length=50, verbose_name='ฟิลด์')),
                ('value', models.CharField(max_length=200, verbose_name='ค่า')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
            ],
            options={
                'verbose_name': 'ค่าอ้างอิงฟอร์ม',
                'verbose_name_plural': 'ค่าอ้างอิงฟอร์ม',
                'ordering': ['field', 'order', 'value'],
                'constraints': [models.UniqueConstraint(fields=('field', 'value'), name='uniq_reference_field_value')],
            },
        ),
    ]
