# Generated by Django 5.2.17 on 2026-09-03 01:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_must_change_password'),
        ('bookings', '0006_referencevalue'),
        ('resources', '0003_alter_blackout_room_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLodgingCohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='เช่น หลักสูตรชั้นนายร้อย เหล่า ส. รุ่นที่ 70', max_length=200, verbose_name='ชื่อหลักสูตร/รุ่น')),
                ('slug', models.SlugField(help_text='ใช้ในลิงก์แชร์ เช่น nr-70', unique=True, verbose_name='รหัสลิงก์ (URL slug)')),
                ('check_in_date', models.DateField(verbose_name='วันที่เริ่มเข้าพัก')),
                ('check_out_date', models.DateField(verbose_name='วันที่สิ้นสุดการเข้าพัก')),
                ('beds_per_room', models.PositiveIntegerField(default=4, verbose_name='จำนวนคน/เตียงต่อห้อง')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดรับการจอง')),
                ('note', models.TextField(blank=True, verbose_name='คำชี้แจง/ข้อปฏิบัติในการเข้าพัก')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('rooms', models.ManyToManyField(limit_choices_to={'resource_type': 'room', 'room_category': 'lodging'}, related_name='course_cohorts', to='resources.resource', verbose_name='ห้องพักที่เปิดให้จอง')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_lodging_cohorts', to=settings.AUTH_USER_MODEL, verbose_name='ผู้กำกับหลักสูตร')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.unit', verbose_name='หน่วยจัดการศึกษา')),
            ],
            options={
                'verbose_name': 'รอบจองที่พักหลักสูตร',
                'verbose_name_plural': 'รอบจองที่พักหลักสูตร',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseStudentLodging',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_number', models.PositiveSmallIntegerField(default=1, verbose_name='เตียงที่')),
                ('rank', models.CharField(max_length=50, verbose_name='ยศ')),
                ('full_name', models.CharField(max_length=150, verbose_name='ชื่อ-นามสกุล')),
                ('origin_unit', models.CharField(max_length=150, verbose_name='หน่วยต้นสังกัด')),
                ('phone', models.CharField(max_length=30, verbose_name='เบอร์โทรศัพท์')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุเพิ่มเติม')),
                ('booked_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่จอง')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='bookings.courselodgingcohort', verbose_name='รอบหลักสูตร')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_lodgings', to='resources.resource', verbose_name='ห้องพัก')),
            ],
            options={
                'verbose_name': 'การจองห้องพักนักเรียน',
                'verbose_name_plural': 'การจองห้องพักนักเรียน',
                'ordering': ['room__code', 'bed_number'],
                'constraints': [models.UniqueConstraint(fields=('cohort', 'room', 'bed_number'), name='unique_cohort_room_bed'), models.UniqueConstraint(fields=('cohort', 'phone'), name='unique_cohort_student_phone')],
            },
        ),
    ]
