# Generated by Django 5.2

import re

from django.db import migrations, models


def _local_normalize_phone(raw_phone):
    return re.sub(r"[^0-9]", "", raw_phone or "").strip()


def preflight_legacy_data(apps, schema_editor):
    Cohort = apps.get_model("bookings", "CourseLodgingCohort")
    Student = apps.get_model("bookings", "CourseStudentLodging")

    for cohort in Cohort.objects.all().iterator():
        if cohort.check_out_date < cohort.check_in_date:
            raise RuntimeError(
                f"Cohort {cohort.slug} has check_out_date < check_in_date (ID: {cohort.pk})"
            )

    phones = {}
    for student in Student.objects.all().iterator():
        normalized = _local_normalize_phone(student.phone)
        if not normalized:
            raise RuntimeError(
                f"Student phone normalizes to empty string (ID: {student.pk}, raw: {student.phone})"
            )
        phones.setdefault((student.cohort_id, normalized), []).append(student.pk)

    duplicates = {key: ids for key, ids in phones.items() if len(ids) > 1}
    if duplicates:
        report = "; ".join(
            f"Cohort {cohort_id}, phone {phone}: IDs {[str(item) for item in ids]}"
            for (cohort_id, phone), ids in duplicates.items()
        )
        raise RuntimeError("Duplicate normalized phones detected in same cohort: " + report)


def migrate_legacy_data(apps, schema_editor):
    Cohort = apps.get_model("bookings", "CourseLodgingCohort")
    Student = apps.get_model("bookings", "CourseStudentLodging")

    for cohort in Cohort.objects.all().iterator():
        has_rooms = cohort.rooms.exists()
        cohort.allocation_status = "allocated" if has_rooms else "released"
        if not has_rooms:
            cohort.is_active = False
        cohort.save(update_fields=["allocation_status", "is_active"])

    for student in Student.objects.all().iterator():
        normalized = _local_normalize_phone(student.phone)
        if student.phone != normalized:
            student.phone = normalized
            student.save(update_fields=["phone"])


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_courselodgingcohort_coursestudentlodging"),
    ]

    operations = [
        migrations.RunPython(preflight_legacy_data, migrations.RunPython.noop),
        migrations.AddField(
            model_name="courselodgingcohort",
            name="allocation_status",
            field=models.CharField(
                choices=[
                    ("allocated", "จัดสรรห้องพัก (สงวนห้อง)"),
                    ("released", "ปลดการสงวนห้อง (ยังไม่จัดสรร/เสร็จสิ้น)"),
                ],
                default="released",
                max_length=20,
                verbose_name="สถานะการจัดสรรห้องพัก",
            ),
        ),
        migrations.AlterField(
            model_name="courselodgingcohort",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="เปิดรับการจอง"),
        ),
        migrations.RunPython(migrate_legacy_data, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="courselodgingcohort",
            constraint=models.CheckConstraint(
                condition=~models.Q(allocation_status="released", is_active=True),
                name="check_released_cohort_cannot_be_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="courselodgingcohort",
            constraint=models.CheckConstraint(
                condition=models.Q(check_out_date__gte=models.F("check_in_date")),
                name="check_cohort_checkout_after_checkin",
            ),
        ),
    ]
