# Generated by Django 5.2.17 on 2026-09-05 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_courselodgingcohort_state_constraints_and_phone_clean'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestudentlodging',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เวลารายงานตัว'),
        ),
        migrations.AddField(
            model_name='coursestudentlodging',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_lodging_students', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ยืนยันรายงานตัว'),
        ),
    ]
