# Generated by Django 5.2.17 on 2026-09-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0009_coursestudentlodging_checked_in_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="online_meeting_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="ลิงก์ห้องเรียนออนไลน์"
            ),
        ),
    ]
