# Generated by Django 5.2.17 on 2026-09-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_booking_online_meeting_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencevalue",
            name="field",
            field=models.CharField(
                choices=[
                    ("title", "ชื่อกิจกรรม / วิชา"),
                    ("responsible_name", "ผู้รับผิดชอบ"),
                    ("responsible_phone", "โทรศัพท์ผู้รับผิดชอบ"),
                    ("attendee_level", "ระดับ/ชั้นผู้เข้าร่วม"),
                    ("layout", "รูปแบบจัดโต๊ะ"),
                    ("time_preset", "ช่วงเวลาสำเร็จรูป (รูปแบบ HHMM-HHMM|ป้ายชื่อ)"),
                ],
                max_length=50,
                verbose_name="ฟิลด์",
            ),
        ),
    ]
