# Generated by Django 5.2.17 on 2026-09-20 22:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_favorite_resources'),
        ('bookings', '0011_alter_referencevalue_field'),
        ('resources', '0005_alter_blackout_room_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicLodgingAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
            ],
            options={
                'verbose_name': 'ลิงก์ติดตามคำขอที่พักบุคคลทั่วไป',
                'verbose_name_plural': 'ลิงก์ติดตามคำขอที่พักบุคคลทั่วไป',
            },
        ),
        migrations.AddField(
            model_name='courselodgingcohort',
            name='booking_close_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ปิดรับจองเมื่อ'),
        ),
        migrations.AddField(
            model_name='courselodgingcohort',
            name='booking_open_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เปิดรับจองเมื่อ'),
        ),
        migrations.AlterField(
            model_name='courselodgingcohort',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='เปิดใช้การจองด้วยตนเอง'),
        ),
        migrations.AddConstraint(
            model_name='courselodgingcohort',
            constraint=models.CheckConstraint(condition=models.Q(('booking_open_at__isnull', True), ('booking_close_at__isnull', True), ('booking_close_at__gte', models.F('booking_open_at')), _connector='OR'), name='check_cohort_booking_window_order'),
        ),
        migrations.AddField(
            model_name='publiclodgingaccess',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_lodging_access', to='bookings.booking', verbose_name='คำขอจองที่พัก'),
        ),
    ]
