# Generated by Django 5.2.17 on 2026-09-21 01:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_publiclodgingaccess_and_more'),
        ('resources', '0005_alter_blackout_room_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLodgingAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_service_access', to='bookings.coursestudentlodging', verbose_name='การจองที่พักนักเรียน')),
            ],
            options={
                'verbose_name': 'ลิงก์จัดการการจองที่พักนักเรียน',
                'verbose_name_plural': 'ลิงก์จัดการการจองที่พักนักเรียน',
            },
        ),
        migrations.CreateModel(
            name='PublicLodgingThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('phone', 'เบอร์โทรศัพท์'), ('client', 'เบราว์เซอร์/เซสชัน')], max_length=16, verbose_name='ขอบเขต')),
                ('key_hash', models.CharField(max_length=64, verbose_name='รหัสแฮช')),
                ('window_start', models.DateTimeField(verbose_name='เริ่มช่วงเวลา')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='จำนวนครั้ง')),
            ],
            options={
                'verbose_name': 'ตัวนับป้องกันคำขอที่พักซ้ำถี่',
                'verbose_name_plural': 'ตัวนับป้องกันคำขอที่พักซ้ำถี่',
                'indexes': [models.Index(fields=['window_start'], name='bookings_pu_window__9bb691_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'key_hash', 'window_start'), name='unique_public_lodging_throttle_window')],
            },
        ),
        migrations.CreateModel(
            name='CourseLodgingRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_student_id', models.UUIDField(unique=True, verbose_name='รหัสการจองเดิม')),
                ('bed_number', models.PositiveSmallIntegerField(verbose_name='เตียงเดิม')),
                ('rank', models.CharField(max_length=50, verbose_name='ยศ')),
                ('full_name', models.CharField(max_length=150, verbose_name='ชื่อ-นามสกุล')),
                ('origin_unit', models.CharField(max_length=150, verbose_name='หน่วยต้นสังกัด')),
                ('phone', models.CharField(max_length=30, verbose_name='เบอร์โทรศัพท์')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุเดิม')),
                ('booked_at', models.DateTimeField(verbose_name='เวลาที่จองเดิม')),
                ('outcome', models.CharField(choices=[('cancelled', 'ยกเลิก'), ('no_show', 'ไม่มารายงานตัว')], max_length=20, verbose_name='ผลการปล่อยเตียง')),
                ('channel', models.CharField(choices=[('self_service', 'นักเรียนยกเลิกเอง'), ('staff', 'เจ้าหน้าที่ดำเนินการ')], max_length=20, verbose_name='ช่องทาง')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='เหตุผล')),
                ('released_at', models.DateTimeField(auto_now_add=True, verbose_name='ปล่อยเตียงเมื่อ')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='bookings.courselodgingcohort', verbose_name='รอบหลักสูตร')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_course_lodgings', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ดำเนินการ')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_lodging_releases', to='resources.resource', verbose_name='ห้องพักเดิม')),
            ],
            options={
                'verbose_name': 'ประวัติการปล่อยเตียงนักเรียน',
                'verbose_name_plural': 'ประวัติการปล่อยเตียงนักเรียน',
                'ordering': ['-released_at'],
                'indexes': [models.Index(fields=['cohort', 'outcome', 'released_at'], name='bookings_co_cohort__2620f6_idx')],
            },
        ),
    ]
