# Generated by Django 5.2.17 on 2026-09-21 02:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_courselodgingaccess_publiclodgingthrottle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True, verbose_name='รหัสหลักสูตร')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='ชื่อหลักสูตร')),
                ('include_year_in_label', models.BooleanField(default=False, verbose_name='แสดงปีต่อท้ายเลขรุ่น')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
            ],
            options={
                'verbose_name': 'หลักสูตร',
                'verbose_name_plural': 'หลักสูตร',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=70, unique=True, verbose_name='รหัสรุ่น')),
                ('run_number', models.PositiveIntegerField(verbose_name='รุ่นที่')),
                ('year_code', models.CharField(blank=True, max_length=4, verbose_name='ปีที่แสดงต่อท้าย')),
                ('start_date', models.DateField(verbose_name='วันที่เริ่มหลักสูตร')),
                ('end_date', models.DateField(verbose_name='วันที่สิ้นสุดหลักสูตร')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='bookings.course', verbose_name='หลักสูตร')),
            ],
            options={
                'verbose_name': 'รุ่นหลักสูตร',
                'verbose_name_plural': 'รุ่นหลักสูตร',
                'ordering': ['-start_date', 'course__name', '-run_number'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='course_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.courserun', verbose_name='รุ่นหลักสูตร'),
        ),
        migrations.AddField(
            model_name='courselodgingcohort',
            name='course_run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lodging_cohort', to='bookings.courserun', verbose_name='รุ่นหลักสูตรกลาง'),
        ),
        migrations.AddConstraint(
            model_name='courserun',
            constraint=models.UniqueConstraint(fields=('course', 'run_number', 'year_code'), name='uniq_course_run_number_year'),
        ),
        migrations.AddConstraint(
            model_name='courserun',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='check_course_run_end_after_start'),
        ),
    ]
