# Generated by Django 5.2.17 on 2026-09-27 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_course_courserun_booking_course_run_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courselodgingrelease',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เวลารายงานตัวเดิม'),
        ),
        migrations.AddField(
            model_name='courselodgingrelease',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_course_lodgings', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ยืนยันรายงานตัวเดิม'),
        ),
        migrations.AlterField(
            model_name='courselodgingrelease',
            name='outcome',
            field=models.CharField(choices=[('cancelled', 'ยกเลิก'), ('no_show', 'ไม่มารายงานตัว'), ('checked_out', 'ออกจากที่พัก')], max_length=20, verbose_name='ผลการปล่อยเตียง'),
        ),
    ]
