# Generated by Django 5.2.17 on 2026-10-03 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_courselodgingrelease_checked_in_at_and_more'),
        ('resources', '0006_online_room_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='อีเมลโรงเรียน')),
                ('rank', models.CharField(blank=True, max_length=50, verbose_name='ยศ')),
                ('origin_unit', models.CharField(blank=True, max_length=150, verbose_name='หน่วยต้นสังกัด')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='เบอร์โทรศัพท์')),
                ('is_active', models.BooleanField(default=True, verbose_name='อนุญาตให้จองเตียง')),
            ],
            options={
                'verbose_name': 'รายชื่อนักเรียนที่มีสิทธิ์จองเตียง',
                'verbose_name_plural': 'รายชื่อนักเรียนที่มีสิทธิ์จองเตียง',
            },
        ),
        migrations.AddField(
            model_name='coursestudentlodging',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_student_lodgings', to=settings.AUTH_USER_MODEL, verbose_name='เจ้าของบัญชี'),
        ),
        migrations.AddConstraint(
            model_name='coursestudentlodging',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('cohort', 'user'), name='unique_cohort_student_user'),
        ),
        migrations.AddField(
            model_name='coursestudentenrollment',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='bookings.courselodgingcohort', verbose_name='รุ่นหลักสูตร'),
        ),
        migrations.AddField(
            model_name='coursestudentenrollment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='บัญชีที่ยืนยันแล้ว'),
        ),
        migrations.AddConstraint(
            model_name='coursestudentenrollment',
            constraint=models.UniqueConstraint(fields=('cohort', 'email'), name='unique_cohort_enrollment_email'),
        ),
    ]
