# Generated by Django 5.2.17 on 2026-10-04 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_coursestudentenrollment_coursestudentlodging_user_and_more'),
        ('resources', '0008_seed_lodging_cooling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='ประเภทผู้พัก')),
                ('cooling', models.CharField(choices=[('air', 'แอร์'), ('fan', 'พัดลม')], max_length=8, verbose_name='แอร์/พัดลม')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อวัน')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อเดือน (แสดงเพื่อเปรียบเทียบ)')),
                ('effective_from', models.DateField(verbose_name='มีผลตั้งแต่')),
                ('basis', models.CharField(choices=[('person', 'ต่อคน'), ('room', 'ต่อห้อง')], default='person', max_length=8, verbose_name='หน่วยคิดเงิน')),
            ],
            options={
                'verbose_name': 'อัตราค่าที่พัก',
                'verbose_name_plural': 'อัตราค่าที่พัก',
                'ordering': ['category', 'cooling', '-effective_from'],
                'constraints': [models.UniqueConstraint(fields=('category', 'cooling', 'effective_from'), name='unique_lodging_rate_date'), models.CheckConstraint(condition=models.Q(('daily_price__gte', 0), ('monthly_price__gte', 0)), name='nonnegative_lodging_rate')],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='lodging_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guest_bookings', to='bookings.lodgingrate', verbose_name='อัตราค่าที่พักที่เจ้าหน้าที่เลือก'),
        ),
        migrations.AddField(
            model_name='coursestudentlodging',
            name='lodging_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='bookings.lodgingrate', verbose_name='อัตราค่าที่พักที่เจ้าหน้าที่เลือก'),
        ),
        migrations.CreateModel(
            name='LodgingMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='วันเข้าพัก')),
                ('check_out_date', models.DateField(verbose_name='วันออก')),
                ('meter_in', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='เลขมิเตอร์เข้า')),
                ('meter_out', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='เลขมิเตอร์ออก')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='ราคาค่าไฟต่อหน่วย')),
                ('recorded_at', models.DateTimeField(auto_now=True, verbose_name='เวลาบันทึกล่าสุด')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lodging_meters', to='resources.resource', verbose_name='ห้องแอร์')),
            ],
            options={
                'verbose_name': 'มิเตอร์ไฟห้องพัก',
                'verbose_name_plural': 'มิเตอร์ไฟห้องพัก',
                'constraints': [models.UniqueConstraint(fields=('room', 'check_in_date', 'check_out_date'), name='unique_room_stay_meter'), models.CheckConstraint(condition=models.Q(('check_out_date__gte', models.F('check_in_date'))), name='meter_stay_dates_valid'), models.CheckConstraint(condition=models.Q(('meter_in__gte', 0), models.Q(('meter_out__isnull', True), ('meter_out__gte', models.F('meter_in')), _connector='OR')), name='meter_values_valid'), models.CheckConstraint(condition=models.Q(('unit_price__isnull', True), ('unit_price__gte', 0), _connector='OR'), name='meter_price_nonnegative')],
            },
        ),
    ]
