# Generated by Django 5.2.17 on 2026-10-03 22:43

from django.db import migrations
from datetime import date
from decimal import Decimal


def seed_rates(apps, schema_editor):
    Rate = apps.get_model('bookings', 'LodgingRate')
    # Fixed snapshot of lodging_about_data.RATES. Monthly prices are comparison only.
    rates = [
        ('บุคคลภายนอก', '150', '2500', '100', '2000'),
        ('นขต.กรม.สส.', '100', '2000', '70', '1500'),
        ('นขต.รร.ส.สส.', '50', '1500', '40', '800'),
        ('นายทหารนักเรียน', '50', '1500', '40', '800'),
        ('นายสิบนักเรียน', '40', '1000', '30', '800'),
    ]
    for category, air_day, air_month, fan_day, fan_month in rates:
        for cooling, daily, monthly in [('air', air_day, air_month), ('fan', fan_day, fan_month)]:
            Rate.objects.using(schema_editor.connection.alias).get_or_create(
                category=category, cooling=cooling, effective_from=date(2026, 10, 3),
                defaults={'daily_price': Decimal(daily), 'monthly_price': Decimal(monthly), 'basis': 'person'},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_lodging_dashboard_billing'),
    ]

    operations = [
        migrations.RunPython(seed_rates, migrations.RunPython.noop),
    ]
