# Generated by Django 5.2.17 on 2026-10-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_seed_lodging_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselodgingcohort',
            name='open_enrollment',
            field=models.BooleanField(default=True, help_text='ปิดเมื่อต้องการให้จองได้เฉพาะอีเมลที่เจ้าหน้าที่ใส่ในรายชื่อรุ่นไว้ก่อน', verbose_name='เข้าสู่ระบบด้วยอีเมลโรงเรียนแล้วจองได้ทันที'),
        ),
    ]
