# Generated by Django 5.2.17 on 2026-08-23 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_booking_decision_reason_booking_sla_escalated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'ส่งคำขอ'), ('approved', 'อนุมัติ'), ('rejected', 'ปฏิเสธ'), ('expired', 'หมดอายุ')], max_length=20, verbose_name='การพิจารณา')),
                ('reason', models.TextField(blank=True, verbose_name='เหตุผล')),
                ('acted_at', models.DateTimeField(auto_now_add=True, verbose_name='ดำเนินการเมื่อ')),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions', to=settings.AUTH_USER_MODEL, verbose_name='ดำเนินการโดย')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='bookings.booking', verbose_name='การจอง')),
                ('on_behalf_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions_on_behalf', to=settings.AUTH_USER_MODEL, verbose_name='รักษาการแทน')),
            ],
            options={
                'verbose_name': 'ประวัติการพิจารณา',
                'verbose_name_plural': 'ประวัติการพิจารณา',
                'ordering': ['acted_at', 'pk'],
                'indexes': [models.Index(fields=['booking', 'acted_at'], name='approvals_a_booking_0926e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApproverDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='ตั้งแต่วันที่')),
                ('end_date', models.DateField(verbose_name='ถึงวันที่')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegations_received', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รักษาการ')),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegations_given', to=settings.AUTH_USER_MODEL, verbose_name='ผู้มอบหมาย')),
            ],
            options={
                'verbose_name': 'ผู้รักษาการแทน',
                'verbose_name_plural': 'ผู้รักษาการแทน',
                'ordering': ['-start_date', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='delegation_end_on_or_after_start'), models.CheckConstraint(condition=models.Q(('delegator', models.F('delegate')), _negated=True), name='delegation_different_users')],
            },
        ),
    ]
