# Generated by Django 5.2.17 on 2026-08-24 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
        ('bookings', '0005_bookingamendment_preemption_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='amendment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='bookings.bookingamendment', verbose_name='คำขอแก้ไข'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='action',
            field=models.CharField(choices=[('submitted', 'ส่งคำขอ'), ('approved', 'อนุมัติ'), ('rejected', 'ปฏิเสธ'), ('expired', 'หมดอายุ'), ('withdrawn', 'ถอนคำขอแก้ไข')], max_length=20, verbose_name='การพิจารณา'),
        ),
        migrations.AddConstraint(
            model_name='approval',
            constraint=models.CheckConstraint(condition=models.Q(('booking__isnull', False), ('amendment__isnull', False), _connector='OR'), name='approval_has_booking_or_amendment'),
        ),
    ]
