# Generated by Django 5.2.17 on 2026-08-23 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_booking_decision_reason_booking_sla_escalated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='ข้อความ')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='ลิงก์')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='อ่านเมื่อ')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookings.booking', verbose_name='การจอง')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับ')),
            ],
            options={
                'verbose_name': 'การแจ้งเตือน',
                'verbose_name_plural': 'การแจ้งเตือน',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='notificatio_user_id_47e85c_idx')],
            },
        ),
    ]
