# Generated by Django 5.2.17 on 2026-10-03 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0015_courselodgingrelease_checked_in_at_and_more"),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=30,
                verbose_name="ชนิดการแจ้งเตือน",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", ""), _negated=True),
                fields=("booking", "user", "kind"),
                name="uniq_notification_booking_user_kind",
            ),
        ),
    ]
