# Generated by Django 5.2.17 on 2026-10-04 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=2048, unique=True, verbose_name='ปลายทางแจ้งเตือน')),
                ('p256dh', models.CharField(max_length=100, verbose_name='กุญแจเข้ารหัสจากเบราว์เซอร์')),
                ('auth', models.CharField(max_length=30, verbose_name='กุญแจยืนยันจากเบราว์เซอร์')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='เบราว์เซอร์')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ลงทะเบียนเมื่อ')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='ส่งสำเร็จล่าสุด')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='จำนวนครั้งที่ส่งไม่สำเร็จ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับ')),
            ],
            options={
                'verbose_name': 'เครื่องรับแจ้งเตือน',
                'verbose_name_plural': 'เครื่องรับแจ้งเตือน',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
