# Generated by Django 5.2.17 on 2026-08-22 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('room', 'ห้อง'), ('equipment', 'อุปกรณ์ส่วนกลาง')], default='room', max_length=20, verbose_name='ประเภททรัพยากร')),
                ('code', models.CharField(help_text='เช่น B2-301 หรือ PROJ-05', max_length=30, unique=True, verbose_name='รหัส')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อ')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='อาคาร')),
                ('floor', models.CharField(blank=True, max_length=20, verbose_name='ชั้น')),
                ('location_note', models.CharField(blank=True, max_length=200, verbose_name='ที่ตั้งเพิ่มเติม')),
                ('room_category', models.CharField(choices=[('classroom', 'ห้องเรียน'), ('lab', 'ห้องสอนปฏิบัติ'), ('meeting', 'ห้องประชุม'), ('special', 'ห้องพิเศษ'), ('none', '— (อุปกรณ์)')], default='classroom', max_length=20, verbose_name='ประเภทห้อง')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='0 = ไม่กำหนด ระบบเตือนเมื่อเกิน ไม่บล็อก', verbose_name='ความจุ (คน)')),
                ('fixed_equipment', models.TextField(blank=True, help_text='บรรทัดละรายการ', verbose_name='อุปกรณ์ประจำห้อง')),
                ('layouts', models.TextField(blank=True, help_text='บรรทัดละรายการ', verbose_name='รูปแบบจัดโต๊ะที่รองรับ')),
                ('status', models.CharField(choices=[('active', 'ใช้งาน'), ('out_of_service', 'งดใช้ชั่วคราว'), ('retired', 'ปลดระวาง')], default='active', max_length=20, verbose_name='สถานะ')),
                ('custodians', models.ManyToManyField(blank=True, related_name='custodied_resources', to=settings.AUTH_USER_MODEL, verbose_name='เจ้าหน้าที่ดูแล')),
                ('owner_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_resources', to='accounts.unit', verbose_name='หน่วยเจ้าของ')),
            ],
            options={
                'verbose_name': 'ทรัพยากร (ห้อง/อุปกรณ์)',
                'verbose_name_plural': 'ทรัพยากร (ห้อง/อุปกรณ์)',
                'ordering': ['building', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ResourceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_policy', models.CharField(choices=[('auto', 'อัตโนมัติเมื่อว่าง'), ('required', 'ต้องอนุมัติ')], default='auto', max_length=20, verbose_name='นโยบายอนุมัติ')),
                ('max_advance_days', models.PositiveIntegerField(default=90, verbose_name='จองล่วงหน้าสูงสุด (วัน)')),
                ('cancel_cutoff_hours', models.PositiveIntegerField(default=4, verbose_name='แก้ไข/ยกเลิกได้ถึงก่อนเริ่ม (ชม.)')),
                ('buffer_before_min', models.PositiveIntegerField(default=0, verbose_name='Buffer ก่อน (นาที)')),
                ('buffer_after_min', models.PositiveIntegerField(default=0, verbose_name='Buffer หลัง (นาที)')),
                ('service_start', models.TimeField(default='07:30', verbose_name='เปิดให้บริการ')),
                ('service_end', models.TimeField(default='17:00', verbose_name='ปิดให้บริการ')),
                ('min_duration_min', models.PositiveIntegerField(default=30, verbose_name='ระยะจองขั้นต่ำ (นาที)')),
                ('max_duration_min', models.PositiveIntegerField(default=1440, verbose_name='ระยะจองสูงสุดต่อครั้ง (นาที)')),
                ('allow_series', models.BooleanField(default=True, verbose_name='จองเป็นชุดได้')),
                ('max_series_occurrences', models.PositiveIntegerField(default=20, verbose_name='จำนวนครั้งสูงสุดต่อชุด')),
                ('allowed_units', models.ManyToManyField(blank=True, help_text='เว้นว่าง = ทุกหน่วย', to='accounts.unit', verbose_name='หน่วยที่จองได้')),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='resources.resource', verbose_name='ทรัพยากร')),
            ],
            options={
                'verbose_name': 'กฎรายห้อง',
                'verbose_name_plural': 'กฎรายห้อง',
            },
        ),
        migrations.CreateModel(
            name='ResourceApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='ไม่ติ๊ก = ผู้อนุมัติสำรอง', verbose_name='ผู้อนุมัติหลัก')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='resources.resource', verbose_name='ห้อง')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approver_of', to=settings.AUTH_USER_MODEL, verbose_name='ผู้อนุมัติ')),
            ],
            options={
                'verbose_name': 'ผู้อนุมัติของห้อง',
                'verbose_name_plural': 'ผู้อนุมัติของห้อง',
                'constraints': [models.UniqueConstraint(fields=('resource', 'user'), name='uniq_approver_per_resource'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('resource',), name='one_primary_approver_per_resource')],
            },
        ),
    ]
