# Generated by Django 5.2.17 on 2026-08-23 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blackout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อวันหยุด/กิจกรรม')),
                ('start_at', models.DateTimeField(verbose_name='เริ่ม')),
                ('end_at', models.DateTimeField(verbose_name='สิ้นสุด')),
                ('scope', models.CharField(choices=[('all', 'ทุกห้อง'), ('building', 'อาคาร'), ('category', 'ประเภทห้อง'), ('rooms', 'ห้องที่เลือก')], default='all', max_length=20, verbose_name='ขอบเขต')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='อาคาร')),
                ('room_category', models.CharField(blank=True, choices=[('classroom', 'ห้องเรียน'), ('lab', 'ห้องสอนปฏิบัติ'), ('meeting', 'ห้องประชุม'), ('special', 'ห้องพิเศษ'), ('none', '— (อุปกรณ์)')], max_length=20, verbose_name='ประเภทห้อง')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_blackouts', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
                ('rooms', models.ManyToManyField(blank=True, limit_choices_to={'resource_type': 'room'}, related_name='blackouts', to='resources.resource', verbose_name='ห้องที่เลือก')),
            ],
            options={
                'verbose_name': 'ปฏิทินส่วนกลาง',
                'verbose_name_plural': 'ปฏิทินส่วนกลาง',
                'ordering': ['start_at', 'title'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='blackout_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='ResourceOutage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='เริ่มงดใช้')),
                ('end_at', models.DateTimeField(verbose_name='สิ้นสุดงดใช้')),
                ('reason', models.CharField(max_length=200, verbose_name='เหตุผล')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('ended_early_at', models.DateTimeField(blank=True, null=True, verbose_name='สิ้นสุดก่อนกำหนดเมื่อ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_resource_outages', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
                ('resource', models.ForeignKey(limit_choices_to={'resource_type': 'room'}, on_delete=django.db.models.deletion.PROTECT, related_name='outages', to='resources.resource', verbose_name='ห้อง')),
            ],
            options={
                'verbose_name': 'ช่วงงดใช้ห้อง',
                'verbose_name_plural': 'ช่วงงดใช้ห้อง',
                'ordering': ['-start_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='outage_end_after_start')],
            },
        ),
    ]
