# Generated by Django 5.2.17 on 2026-09-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_blackout_resourceoutage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackout',
            name='room_category',
            field=models.CharField(blank=True, choices=[('classroom', 'ห้องเรียน'), ('lab', 'ห้องสอนปฏิบัติ'), ('meeting', 'ห้องประชุม'), ('lodging', 'ห้องพัก'), ('special', 'ห้องพิเศษ'), ('none', '— (อุปกรณ์)')], max_length=20, verbose_name='ประเภทห้อง'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='room_category',
            field=models.CharField(choices=[('classroom', 'ห้องเรียน'), ('lab', 'ห้องสอนปฏิบัติ'), ('meeting', 'ห้องประชุม'), ('lodging', 'ห้องพัก'), ('special', 'ห้องพิเศษ'), ('none', '— (อุปกรณ์)')], default='classroom', max_length=20, verbose_name='ประเภทห้อง'),
        ),
    ]
