# Generated by Django 5.2.17 on 2026-09-05 02:30

import django.db.models.deletion
import resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_blackout_room_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=resources.models.room_photo_upload_to, validators=[resources.models.validate_room_photo_file], verbose_name='รูปภาพ')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='คำอธิบายภาพ')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ลำดับ')),
                ('is_cover', models.BooleanField(default=False, verbose_name='ใช้เป็นรูปหน้าปก')),
                ('resource', models.ForeignKey(limit_choices_to={'resource_type': 'room'}, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='resources.resource', verbose_name='ห้อง')),
            ],
            options={
                'verbose_name': 'รูปห้อง',
                'verbose_name_plural': 'รูปห้อง',
                'ordering': ['-is_cover', 'order', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('resource',), name='unique_cover_photo_per_resource', violation_error_message='ห้องนี้มีรูปหน้าปกอยู่แล้ว กรุณายกเลิกรูปหน้าปกเดิมก่อน หรือเลือกรูปนี้เป็นปกภายหลัง')],
            },
        ),
    ]
