# Generated by Django 5.2.17 on 2026-10-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_online_room_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='lodging_cooling',
            field=models.CharField(blank=True, choices=[('air', 'แอร์'), ('fan', 'พัดลม')], db_default='', default='', max_length=8, verbose_name='ประเภทห้องพัก'),
        ),
    ]
