# Generated by Django 5.2.17 on 2026-10-03 22:43

from django.db import migrations


def seed_cooling(apps, schema_editor):
    # Snapshot of lodging_about_data.py; never overwrite an operator's setting.
    Resource = apps.get_model('resources', 'Resource')
    groups = {
        'air': list(range(401, 408)) + list(range(411, 417)) + list(range(449, 461)) + list(range(501, 531)),
        'fan': list(range(417, 449)),
    }
    for cooling, numbers in groups.items():
        codes = [code for number in numbers for code in (str(number), f'DORM-{number}')]
        Resource.objects.using(schema_editor.connection.alias).filter(
            resource_type='room', room_category='lodging', lodging_cooling='', code__in=codes,
        ).update(lodging_cooling=cooling)


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_resource_lodging_cooling'),
    ]

    operations = [
        migrations.RunPython(seed_cooling, migrations.RunPython.noop),
    ]
